### PR TITLE
remove !ar command

### PR DESCRIPTION
**Pull request by robinferch**

### CODE REVIEW

**Comment by robinferch** [comment]
Ignore this, this was by accident xD

**Comment by XboxBedrock** [comment]
Ok lol but why would one remove ar

**Comment by robinferch** [comment]
I dont know, BTE Germany supporters wanted to remove that. Makes no sense in my opinion

**Comment by XboxBedrock** [comment]
Hm yeah merge into their fork then?

**Comment by robinferch** [comment]
that was actually my mistake, i misslicheres and created a pr in this repo instead

**Comment by XboxBedrock** [comment]
Ah ok

**Pull request closed without merging**
